// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBUXLF6Rbjepn1dDCEW52CZcT1skbFuujQ',
    appId: '1:10862777026:web:f7c484e2d712d77596215b',
    messagingSenderId: '10862777026',
    projectId: 'atopa-tfg',
    authDomain: 'atopa-tfg.firebaseapp.com',
    storageBucket: 'atopa-tfg.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBE_RMquLneUqauXdwx1HP8MCMA_MCL7H0',
    appId: '1:10862777026:android:b75f8f94532ad88f96215b',
    messagingSenderId: '10862777026',
    projectId: 'atopa-tfg',
    storageBucket: 'atopa-tfg.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBgcDWNn0E36e4SrVk4uqIIjnKSdhbscE0',
    appId: '1:10862777026:ios:4b50b9c7524b19d696215b',
    messagingSenderId: '10862777026',
    projectId: 'atopa-tfg',
    storageBucket: 'atopa-tfg.appspot.com',
    iosClientId: '10862777026-kfkvb872m0gal963466d8jacn50llo8s.apps.googleusercontent.com',
    iosBundleId: 'com.example.atopaAppFlutter',
  );
}
